package io.github.zebalu.aoc2021;

public class Day02 {
    public static void main(String[] args) {
        firstPart();
        secondPart();
    }

    private static void firstPart() {
        drive(INPUT, new SimpleSubmarine());
    }

    private static void secondPart() {
        drive(INPUT, new AimingSubmarine());
    }
    
    private static void drive(String lines, AbstractSubmarine submarine) {
        lines.lines().forEach(submarine::applyLine);
        System.out.println(submarine.position());
    }
    
    private static abstract sealed class AbstractSubmarine permits SimpleSubmarine,AimingSubmarine {
        protected int depth;
        protected int horizonalPosition;

        protected abstract void forward(int x);

        protected abstract void down(int x);

        protected abstract void up(int x);

        protected void applyLine(String line) {
            var parts = line.split(" ");
            int amount = Integer.parseInt(parts[1]);
            switch (parts[0]) {
            case "forward" -> forward(amount);
            case "down" -> down(amount);
            case "up" -> up(amount);
            default -> throw new IllegalArgumentException("Unexpected value: " + parts[0]);
            }
        }

        int position() {
            return depth * horizonalPosition;
        }
    }

    private static final class SimpleSubmarine extends AbstractSubmarine {

        @Override
        protected void forward(int x) {
            horizonalPosition += x;
        }

        @Override
        protected void down(int x) {
            depth += x;
        }

        @Override
        protected void up(int x) {
            depth -= x;
        }

    }

    private static final class AimingSubmarine extends AbstractSubmarine {
        int aim;

        @Override
        protected void forward(int x) {
            horizonalPosition += x;
            depth += x * aim;
        }

        @Override
        protected void down(int x) {
            aim += x;
        }

        @Override
        protected void up(int x) {
            aim -= x;
        }
    }

    private static final String INPUT = """
            forward 1
            forward 5
            forward 8
            down 9
            down 7
            forward 2
            up 3
            forward 7
            down 1
            down 7
            down 9
            up 2
            up 9
            down 5
            up 7
            forward 6
            down 7
            forward 9
            down 2
            down 5
            forward 5
            down 5
            forward 4
            up 3
            up 2
            down 8
            down 7
            forward 1
            forward 5
            forward 2
            down 8
            forward 3
            down 8
            down 2
            down 1
            forward 7
            down 2
            forward 1
            forward 4
            forward 8
            forward 4
            forward 6
            forward 7
            forward 4
            down 3
            down 3
            down 1
            down 4
            forward 1
            up 5
            down 8
            forward 9
            up 4
            forward 2
            up 5
            forward 7
            forward 9
            up 5
            forward 5
            down 5
            forward 8
            up 6
            up 7
            up 4
            down 4
            up 5
            up 9
            forward 3
            down 9
            down 4
            up 5
            forward 3
            forward 8
            up 4
            down 2
            down 7
            down 2
            down 7
            down 5
            down 7
            down 2
            forward 9
            forward 7
            up 5
            forward 8
            forward 7
            up 5
            forward 6
            up 5
            down 3
            down 9
            up 2
            forward 4
            down 4
            down 3
            forward 4
            down 4
            forward 5
            down 6
            forward 5
            down 4
            down 2
            down 4
            up 8
            up 3
            down 8
            forward 2
            forward 9
            down 5
            down 8
            down 3
            down 2
            up 2
            up 1
            forward 7
            up 3
            down 7
            up 2
            forward 7
            down 2
            forward 9
            down 3
            forward 1
            down 6
            up 1
            forward 8
            down 2
            down 1
            down 1
            up 6
            forward 5
            forward 8
            forward 2
            down 8
            down 2
            forward 6
            down 3
            down 2
            forward 7
            down 6
            down 9
            down 3
            forward 2
            down 8
            forward 2
            up 1
            down 7
            forward 9
            down 9
            forward 1
            down 4
            down 7
            forward 1
            up 4
            down 5
            down 4
            down 3
            up 8
            down 1
            down 8
            up 1
            up 7
            forward 4
            forward 1
            down 4
            forward 7
            down 3
            forward 6
            down 9
            down 6
            down 4
            up 6
            forward 8
            down 5
            forward 9
            down 6
            down 4
            forward 1
            down 6
            down 7
            up 9
            up 4
            up 2
            forward 4
            up 4
            down 9
            down 2
            up 6
            forward 9
            down 5
            down 2
            forward 3
            up 2
            forward 2
            down 4
            forward 3
            up 8
            down 2
            forward 7
            forward 3
            down 9
            forward 6
            down 1
            forward 7
            forward 6
            up 6
            forward 3
            forward 2
            forward 5
            up 5
            down 5
            down 2
            down 9
            down 7
            forward 3
            forward 6
            forward 6
            forward 5
            down 2
            forward 4
            forward 8
            forward 2
            forward 1
            up 4
            up 6
            down 6
            forward 5
            forward 5
            down 6
            down 8
            forward 7
            forward 1
            down 9
            up 8
            down 9
            down 1
            up 4
            down 9
            up 6
            down 5
            forward 4
            forward 2
            down 9
            down 8
            up 6
            down 3
            down 7
            up 5
            forward 6
            down 3
            forward 4
            up 7
            down 8
            forward 3
            down 9
            down 7
            forward 5
            forward 2
            forward 4
            forward 8
            down 2
            forward 6
            forward 9
            down 9
            forward 6
            down 2
            down 8
            up 7
            down 4
            forward 2
            forward 6
            forward 2
            forward 7
            forward 1
            up 1
            up 1
            down 9
            forward 9
            down 7
            up 4
            forward 8
            up 7
            down 3
            forward 3
            forward 7
            down 2
            up 3
            forward 5
            down 5
            forward 1
            down 8
            forward 9
            forward 5
            down 9
            forward 8
            down 3
            up 7
            down 1
            forward 6
            forward 3
            forward 8
            down 3
            down 6
            forward 9
            forward 5
            down 3
            up 7
            forward 2
            forward 6
            up 2
            forward 3
            down 4
            up 8
            down 7
            up 3
            down 2
            down 3
            up 9
            down 2
            forward 7
            up 7
            forward 1
            down 2
            forward 4
            forward 9
            down 6
            forward 5
            forward 1
            down 6
            down 1
            up 8
            up 5
            down 9
            up 4
            forward 4
            down 9
            forward 7
            down 7
            forward 4
            up 3
            down 7
            down 6
            forward 3
            up 5
            down 9
            down 3
            forward 5
            forward 6
            down 7
            up 3
            up 4
            forward 9
            forward 1
            down 1
            down 1
            up 8
            down 2
            down 4
            down 2
            up 4
            down 1
            forward 9
            down 2
            up 3
            up 1
            up 2
            forward 4
            down 2
            forward 7
            forward 7
            down 4
            forward 3
            down 6
            down 8
            forward 5
            down 9
            forward 9
            down 3
            forward 4
            down 6
            down 9
            down 1
            down 5
            down 4
            down 5
            forward 5
            forward 6
            forward 8
            forward 1
            forward 2
            down 8
            down 4
            down 5
            down 2
            up 4
            down 3
            forward 1
            up 9
            down 8
            forward 9
            up 2
            down 9
            forward 6
            up 5
            forward 3
            forward 4
            down 5
            down 7
            down 1
            forward 6
            down 4
            forward 7
            down 3
            up 3
            forward 5
            down 3
            down 1
            down 6
            up 1
            forward 6
            down 2
            down 3
            down 4
            forward 6
            down 1
            forward 3
            down 8
            down 3
            forward 9
            forward 3
            down 6
            up 7
            forward 4
            down 6
            down 9
            forward 6
            down 3
            up 4
            down 8
            forward 7
            up 7
            forward 1
            forward 6
            down 6
            up 4
            down 6
            forward 4
            forward 5
            down 9
            forward 6
            forward 7
            up 3
            forward 7
            forward 6
            forward 8
            down 8
            forward 6
            down 5
            forward 2
            down 1
            forward 9
            down 8
            up 9
            down 1
            forward 6
            down 7
            up 7
            up 3
            down 8
            up 1
            down 9
            down 4
            forward 6
            down 6
            up 2
            up 4
            down 5
            up 2
            forward 2
            down 5
            forward 6
            down 9
            up 8
            down 1
            down 6
            down 2
            up 8
            up 9
            down 6
            forward 2
            down 8
            up 3
            forward 3
            down 9
            forward 5
            forward 3
            forward 8
            up 7
            down 2
            up 5
            down 1
            down 5
            down 9
            forward 6
            up 8
            forward 3
            forward 1
            forward 1
            forward 6
            down 2
            forward 3
            down 3
            forward 8
            forward 4
            up 1
            forward 7
            up 3
            up 6
            forward 9
            up 7
            down 1
            down 1
            down 7
            down 6
            down 6
            up 6
            forward 3
            up 4
            forward 3
            down 6
            down 1
            forward 7
            down 7
            forward 8
            down 5
            down 6
            forward 4
            up 2
            forward 5
            forward 4
            up 5
            down 4
            forward 9
            up 7
            forward 5
            down 7
            down 4
            down 3
            down 4
            down 3
            forward 3
            forward 6
            up 3
            down 9
            up 9
            down 9
            down 8
            forward 7
            forward 1
            up 4
            up 2
            down 5
            forward 6
            down 1
            forward 6
            forward 6
            down 3
            down 1
            forward 9
            forward 7
            up 4
            forward 2
            up 9
            forward 2
            down 5
            down 9
            down 8
            up 2
            down 5
            down 3
            forward 6
            down 4
            up 2
            up 9
            down 4
            forward 4
            up 6
            up 4
            forward 6
            up 1
            forward 9
            up 1
            down 8
            forward 2
            up 5
            up 6
            forward 4
            down 8
            forward 1
            forward 5
            forward 5
            forward 8
            down 3
            down 3
            forward 3
            down 4
            forward 5
            down 2
            forward 1
            down 3
            down 7
            down 1
            down 5
            forward 8
            down 2
            down 3
            up 9
            forward 5
            down 3
            down 8
            down 1
            up 1
            down 2
            up 4
            forward 7
            down 6
            down 9
            down 4
            forward 4
            forward 2
            forward 6
            forward 3
            forward 6
            forward 5
            down 4
            forward 4
            forward 2
            down 3
            up 3
            down 3
            forward 4
            down 3
            up 5
            up 8
            down 5
            forward 2
            forward 7
            up 5
            forward 7
            down 1
            forward 8
            down 2
            down 1
            forward 5
            down 6
            forward 4
            forward 8
            forward 1
            down 9
            down 3
            down 6
            down 5
            down 7
            forward 8
            forward 4
            down 5
            down 3
            down 9
            down 2
            forward 1
            forward 9
            up 2
            forward 3
            down 4
            forward 8
            down 2
            up 6
            up 2
            down 2
            up 7
            down 3
            down 7
            forward 9
            forward 2
            up 2
            forward 6
            down 8
            down 9
            down 8
            down 8
            down 1
            down 3
            up 9
            up 9
            forward 9
            forward 4
            down 4
            down 2
            forward 5
            forward 4
            forward 1
            forward 2
            forward 2
            down 2
            forward 8
            down 6
            forward 7
            forward 4
            down 7
            down 2
            up 2
            down 7
            forward 7
            up 3
            forward 3
            down 3
            forward 5
            forward 2
            down 1
            forward 1
            forward 8
            down 1
            down 9
            down 8
            down 8
            down 7
            down 2
            forward 2
            down 6
            down 2
            up 7
            down 1
            up 6
            forward 5
            down 9
            forward 9
            forward 4
            forward 4
            down 6
            up 3
            forward 5
            forward 6
            down 5
            up 8
            down 1
            down 3
            up 5
            down 2
            down 5
            forward 5
            down 2
            up 9
            forward 3
            up 9
            forward 6
            up 7
            forward 9
            down 8
            up 8
            down 4
            forward 3
            forward 8
            down 5
            down 7
            down 6
            down 4
            up 3
            forward 8
            down 4
            down 7
            up 9
            up 5
            down 6
            up 1
            down 9
            up 4
            down 6
            down 7
            up 4
            forward 5
            up 8
            down 9
            forward 9
            forward 8
            down 7
            up 9
            down 3
            down 2
            down 1
            down 6
            up 3
            up 2
            down 9
            forward 4
            forward 8
            up 7
            forward 1
            down 4
            down 7
            up 5
            forward 9
            forward 2
            down 7
            up 2
            forward 6
            forward 4
            forward 7
            down 7
            down 4
            forward 9
            forward 9
            down 3
            down 4
            up 1
            forward 1
            down 3
            down 5
            down 2
            down 8
            down 5
            forward 4
            forward 7
            forward 7
            down 3
            up 4
            up 3
            forward 2
            forward 8
            forward 1
            up 5
            down 2
            down 1
            forward 7
            forward 7
            forward 4
            forward 8
            down 4
            forward 7
            down 8
            down 4
            forward 3
            forward 9
            forward 6
            forward 6
            forward 6
            down 1
            down 8
            forward 2
            forward 6
            forward 8
            down 1
            forward 9
            forward 5
            forward 6
            down 2
            forward 8
            down 1
            forward 7
            down 7
            down 1
            up 4
            up 3
            forward 6
            forward 2
            forward 8
            forward 2
            down 4
            forward 6
            down 1
            forward 7
            up 5
            forward 4
            forward 3
            forward 6
            down 6
            down 4
            forward 6
            down 7
            down 9
            down 1
            up 5
            up 7
            down 4
            forward 1
            down 4
            up 1
            down 4
            down 1
            up 6
            forward 2
            down 2
            down 5
            down 8
            down 2
            down 9
            down 5
            forward 3
            up 6
            forward 9
            down 7
            up 7
            down 7
            up 7
            up 4
            down 6
            up 5
            down 3
            forward 9
            forward 4
            down 2
            down 1
            up 1
            down 7
            down 7
            forward 7
            down 2
            up 1
            forward 6
            down 3
            forward 5
            forward 3
            down 5
            forward 1
            down 8
            up 2
            forward 9
            down 2
            up 6
            down 7
            forward 1
            forward 2
            down 2
            up 5
            forward 2
            down 8
            forward 3
            up 2
            down 9
            down 6
            up 3
            down 4
            forward 8
            forward 3
            up 7
            down 4
            forward 4
            forward 5
            forward 3
            up 7
            forward 7
            forward 9
            down 4
            forward 3
            down 9
            down 3
            forward 3
            down 3
            forward 7
            up 6
            forward 9
            down 2
            down 8
            up 9
            forward 3
            forward 5
            down 9
            forward 6
            down 2
            up 9
            forward 6
            forward 3
            down 5
            forward 2
            up 1
            down 3
            up 1
            down 2
            down 6
            forward 5
            up 1
            down 2
            forward 1
            forward 5
            down 5
            forward 8
            down 5
            forward 4
            forward 7
            forward 3
            forward 5
            up 5
            forward 4
            down 1
            down 9
            up 8
            down 8
            down 1
            up 1
            down 7
            forward 3""";
}
